[package]
name = "astroport-cw20-ics20"
version = "0.15.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cw20-ics20-orig = { package = "cw20-ics20", version = "0.15" }

[dev-dependencies]
cosmwasm-schema = "1.1"
