[package]
name = "astroport-mocks"
version = "0.1.0"
authors = ["Astroport"]
edition = "2021"
description = "Mock Astroport contracts used for integration testing"
license = "GPL-3.0-only"
repository = "https://github.com/astroport-fi/astroport_ibc"
homepage = "https://astroport.fi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
astroport-ibc = { path = "../astroport-ibc" }
astro-satellite = { path = "../../contracts/satellite" }
astro-satellite-package = { path = "../satellite" }
cosmwasm-std = "1.2.5"
cw-multi-test = { git = "https://github.com/astroport-fi/cw-multi-test.git", rev = "269a2c829d1ad25d67caa4600f72d2a21fb8fdeb" }
anyhow = "1.0.41"
schemars = "0.8.1"
serde = "1.0"
