[package]
name = "astroport-ibc"
version = "1.2.1"
authors = ["Astroport"]
edition = "2021"
description = "Common Astroport IBC types and constants"
license = "GPL-3"
repository = "https://github.com/astroport-fi/astroport_ibc"
homepage = "https://astroport.fi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = "1.1"
