[package]
name = "astro-satellite-package"
version = "0.1.0"
authors = ["Astroport"]
license = "Apache-2.0"
description = "Astroport satellite contract's types"
repository = "https://github.com/astroport-fi/astroport_ibc"
homepage = "https://astroport.fi"
edition = "2021"

[dependencies]
astroport-governance = { git = "https://github.com/astroport-fi/hidden_astroport_governance.git", branch = "release/terra2" }
cosmwasm-std = "1.1"
cosmwasm-schema = "1.1"
