[package]
name = "astro-satellite-package"
version = "1.2.0"
authors = ["Astroport"]
license = "GPL-3.0-only"
description = "Astroport satellite contract's types"
repository = "https://github.com/astroport-fi/astroport_ibc"
homepage = "https://astroport.fi"
edition = "2021"

[dependencies]
astroport-governance = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
