[package]
name = "astro-satellite-package"
version = "1.0.0"
authors = ["Astroport"]
license = "GPL-3-only"
description = "Astroport satellite contract's types"
repository = "https://github.com/astroport-fi/astroport_ibc"
homepage = "https://astroport.fi"
edition = "2021"

[dependencies]
astroport-governance = { git = "https://github.com/astroport-fi/astroport-governance", version = "1" }
cosmwasm-std = "1.1"
cosmwasm-schema = "1.1"
