[package]
name = "ibc-controller-package"
version = "0.1.0"
authors = ["Astroport"]
license = "Apache-2.0"
description = "Astroport ibc-controller contract's types"
repository = "https://github.com/astroport-fi/astroport_ibc"
homepage = "https://astroport.fi"
edition = "2021"

[dependencies]
astroport-governance = { git = "ssh://git@github.com/astroport-fi/hidden_astroport_governance.git" }
cosmwasm-std = "1.1"
cosmwasm-schema = "1.1"
