[package]
name = "ibc-controller-package"
version = "1.0.0"
authors = ["Astroport"]
license = "GPL-3.0-only"
description = "Astroport ibc-controller contract's types"
repository = "https://github.com/astroport-fi/astroport_ibc"
homepage = "https://astroport.fi"
edition = "2021"

[dependencies]
astroport-governance = { workspace = true }
astroport-ibc = { workspace = true }
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
