[package]
name = "ap-ibc-controller"
version = "0.1.1"
authors = ["Astroport"]
license = "GPL-3.0-only"
description = "Astroport ibc-controller contract's types"
repository = "https://github.com/astroport-fi/astroport_ibc"
homepage = "https://astroport.fi"
edition = "2021"

[dependencies]
astroport-governance = { git = "https://github.com/astroport-fi/hidden_astroport_governance.git" }
cosmwasm-schema = "1.1"
