name: Compiled binaries checks

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check-artifacts-size:
    runs-on: ubuntu-latest
    name: Check Artifacts Size
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git/checkouts
            ~/.cargo/git/db
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Artifacts
        run: |
          docker run \
            -v "$GITHUB_WORKSPACE":/code \
            -v ~/.cargo/registry:/usr/local/cargo/registry \
            -v ~/.cargo/git:/usr/local/cargo/git \
            cosmwasm/workspace-optimizer:0.12.13

      - name: Save artifacts cache
        uses: actions/cache/save@v3
        with:
          path: artifacts
          key: ${{ runner.os }}-artifacts-${{ hashFiles('**/Cargo.lock') }}

      - name: Check Artifacts Size
        run: |
          $GITHUB_WORKSPACE/scripts/check_artifacts_size.sh



  cosmwasm-check:
    runs-on: ubuntu-latest
    name: Cosmwasm check
    needs: check-artifacts-size
    steps:
      # We need this only to get Cargo.lock
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Restore cached artifacts
        uses: actions/cache/restore@v3
        with:
          path: artifacts
          key: ${{ runner.os }}-artifacts-${{ hashFiles('**/Cargo.lock') }}
          fail-on-cache-miss: true
      - name: Install cosmwasm-check
        # Uses --debug for compilation speed
        run: cargo install --debug --locked --version 1.3.1 cosmwasm-check
      - name: Cosmwasm check
        run: |
          cosmwasm-check $GITHUB_WORKSPACE/artifacts/*.wasm --available-capabilities staking,cosmwasm_1_1,neutron,iterator,stargate
